service: example
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get

	
plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
